[package]
authors = ["lettenj61 <lettenj61@users.noreply.github.com>"]
name = "tera-cli"
version = "0.1.0"

[dependencies]
clap = "2.22.1"
error-chain = "0.10.0"
log = "0.3.7"
pretty_env_logger = "0.1.0"
serde_json = "0.9.9"
tera = "0.8.1"
